services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    depends_on:
      - database
    command: [ 'sleep', 'infinity' ]
    restart: unless-stopped
    env_file:
      - .env

  database:
    image: public.ecr.aws/docker/library/postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped

volumes:
  postgres_data:
